#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path("#{File.dirname __FILE__}/../lib")

require 'rubygems'
require 'toggl/worktime'

Version = Toggl::Worktime::VERSION
MAX_WORKING_INTERVAL = 10
DAY_BEGIN_HOUR = 6
DEFAULT_TIMEZONE = 'Asia/Tokyo'

driver = Toggl::Worktime::Driver.new(max_working_interval: MAX_WORKING_INTERVAL)

if ARGV.size == 3
  year, month, day = *ARGV.map(&:to_i)
elsif ARGV.size == 2
  year = DateTime.now.year
  month, day = *ARGV.map(&:to_i)
else
  raise ArgumentError, 'Usage: toggl-worktime [YEAR] MONTH DAY'
end

hour = DAY_BEGIN_HOUR
timezone = DEFAULT_TIMEZONE

driver.merge!(year, month, day, hour, timezone)
user = driver.me

puts user['fullname']
puts 'worktime'

driver.write

puts "Total worktime: #{driver.total_time}"
