#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path("#{File.dirname __FILE__}/../lib")

require 'rubygems'
require 'toggl/worktime'

Version = Toggl::Worktime::VERSION
MAX_WORKING_INTERVAL = 10
DAY_BEGIN_HOUR = 6
DEFAULT_TIMEZONE = 'Asia/Tokyo'

driver = Toggl::Worktime::Driver.new(max_working_interval: MAX_WORKING_INTERVAL)

month = ARGV[0].to_i
day = ARGV[1].to_i
hour = DAY_BEGIN_HOUR
timezone = DEFAULT_TIMEZONE

driver.merge!(month, day, hour, timezone)
user = driver.me

puts user['fullname']
puts 'worktime'

driver.write

puts "Total worktime: #{driver.total_time}"
